<a href="https://colab.research.google.com/github/Vinicius-DEV1/Ciencia_de_dados/blob/main/INFERENCIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DESAFIO 1 - INFERÊNCIA
teste

![depressao.jpg]()

# 1^Problema de negócio

Neste desafio, utilizaremos dados de uma pesquisa realizada anualmente nos Estados Unidos para avaliar 

(1) qual o perfil de indivíduos (adultos maiores de 18 anos) com sintomas depressivos nos EUA no período de 2005-2006, e

 (2) se hábitos saudáveis de alimentação e atividade física estão associados a menores índices de depressão nesta população.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
DF_DEMO_PHQ = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/TERA/DESAFIOS/INFERENCIA/Bases de dados/DEMO_PHQ.csv")

In [ ]:
DF_PAG_HEI = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/TERA/DESAFIOS/INFERENCIA/Bases de dados/PAG_HEI.csv")

In [ ]:
DF_DEMO_PHQ.head(10)

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,RIAGENDR,RIDAGEYR,RIDRETH1,DMDEDUC,INDFMINC
0,31130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,85,3,4,4.0
1,31131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,44,4,4,11.0
2,31132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,70,3,5,11.0
3,31134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,73,3,3,12.0
4,31139,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,2,18,2,3,11.0
5,31143,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1,19,3,4,11.0
6,31144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,21,2,3,3.0
7,31149,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,85,3,2,1.0
8,31150,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,79,3,3,3.0
9,31151,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2,59,4,3,7.0

#DEMO_PHQ

In [ ]:
DF_DEMO_PHQ

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,RIAGENDR,RIDAGEYR,RIDRETH1,DMDEDUC,INDFMINC
0,31130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,85,3,4,4.0
1,31131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,44,4,4,11.0
2,31132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,70,3,5,11.0
3,31134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,73,3,3,12.0
4,31139,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,2,18,2,3,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5329,41466,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2,58,5,2,3.0
5330,41468,0.0,2.0,0.0,1.0,1.0,2.0,1.0,3.0,0.0,2,66,1,1,8.0
5331,41469,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,19,4,4,2.0
5332,41472,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,34,3,4,7.0
5333,41473,0.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,1,21,1,2,6.0

**DF_DEMO_PHQ tem 5.334 rows(linhas) e 15 colunas**

In [ ]:
DF_DEMO_PHQ.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5334 entries, 0 to 5333
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      5334 non-null   int64
 1   DPQ010    4836 non-null   float64
 2   DPQ020    4836 non-null   float64
 3   DPQ030    4836 non-null   float64
 4   DPQ040    4836 non-null   float64
 5   DPQ050    4836 non-null   float64
 6   DPQ060    4836 non-null   float64
 7   DPQ070    4836 non-null   float64
 8   DPQ080    4836 non-null   float64
 9   DPQ090    4836 non-null   float64
 10  RIAGENDR  5334 non-null   int64
 11  RIDAGEYR  5334 non-null   int64
 12  RIDRETH1  5334 non-null   int64
 13  DMDEDUC   5334 non-null   int64
 14  INDFMINC  5287 non-null   float64
dtypes: float64(10), int64(5)
memory usage: 625.2 KB

In [ ]:
DF_DEMO_PHQ.isnull().sum()

SEQN          0
DPQ010      498
DPQ020      498
DPQ030      498
DPQ040      498
DPQ050      498
DPQ060      498
DPQ070      498
DPQ080      498
DPQ090      498
RIAGENDR      0
RIDAGEYR      0
RIDRETH1      0
DMDEDUC       0
INDFMINC     47
dtype: int64

In [ ]:
DF_DEMO_PHQ['DPQ010'].unique()

array([nan,  0.,  1.,  2.,  3.,  9.])

# DF_PAG_HEI

In [ ]:
DF_PAG_HEI

,SEQN,PAG_MINW,ADHERENCE,HEI2015C1_TOTALVEG,HEI2015C2_GREEN_AND_BEAN,HEI2015C3_TOTALFRUIT,HEI2015C4_WHOLEFRUIT,HEI2015C5_WHOLEGRAIN,HEI2015C6_TOTALDAIRY,HEI2015C7_TOTPROT,HEI2015C8_SEAPLANT_PROT,HEI2015C9_FATTYACID,HEI2015C10_SODIUM,HEI2015C11_REFINEDGRAIN,HEI2015C12_SFAT,HEI2015C13_ADDSUG,HEI2015_TOTAL_SCORE
0,31128,NaN,NaN,3.083350,0.000000,3.927008,5.000000,0.000000,5.000000,4.251329,0.000000,2.487572,6.911882,10.000000,0.818029,6.408092,47.887262
1,31129,285.450346,2.0,1.697761,0.000000,3.731602,4.929186,0.527631,3.887809,4.693141,0.928562,3.740758,6.146441,7.274979,8.006457,0.000000,45.564326
2,31130,0.000000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31131,264.711316,2.0,3.115103,0.000000,5.000000,1.320674,0.000000,3.141062,4.071959,2.052399,0.684985,2.297100,9.512964,0.438428,3.919226,35.553899
4,31132,1353.348730,3.0,3.509081,0.000000,5.000000,5.000000,5.000000,4.448512,5.000000,0.000000,2.050769,7.369489,8.887880,8.186877,9.099088,63.551696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9419,41469,184.711316,2.0,2.555935,0.000000,2.613733,0.000000,0.000000,2.151846,5.000000,0.000000,9.344947,3.535211,4.326307,5.269780,8.195564,42.993323
9420,41471,951.478060,3.0,2.674192,3.769401,2.198817,0.517369,0.463168,4.662005,5.000000,1.191796,6.145146,3.189620,3.766149,3.974279,7.758940,45.310883
9421,41472,27.713626,1.0,2.457422,2.930799,2.311917,0.000000,0.933303,5.000000,5.000000,5.000000,2.090534,8.409844,8.936854,3.063795,0.000000,46.134467
9422,41473,685.912240,3.0,3.907340,5.000000,0.000000,0.000000,0.000000,5.000000,5.000000,5.000000,0.000000,7.458058,10.000000,1.676912,2.751168,45.793478
9423,41474,0.000000,1.0,1.238646,4.610515,0.688137,0.240848,5.000000,5.000000,4.304982,5.000000,2.162293,7.018993,10.000000,7.541082,0.000000,52.805494

DF_PAG_HEI tem 9.424 rows(linhas) e 17 columns

In [ ]:
DF_PAG_HEI.head()

,SEQN,PAG_MINW,ADHERENCE,HEI2015C1_TOTALVEG,HEI2015C2_GREEN_AND_BEAN,HEI2015C3_TOTALFRUIT,HEI2015C4_WHOLEFRUIT,HEI2015C5_WHOLEGRAIN,HEI2015C6_TOTALDAIRY,HEI2015C7_TOTPROT,HEI2015C8_SEAPLANT_PROT,HEI2015C9_FATTYACID,HEI2015C10_SODIUM,HEI2015C11_REFINEDGRAIN,HEI2015C12_SFAT,HEI2015C13_ADDSUG,HEI2015_TOTAL_SCORE
0,31128,NaN,NaN,3.083350,0.0,3.927008,5.000000,0.000000,5.000000,4.251329,0.000000,2.487572,6.911882,10.000000,0.818029,6.408092,47.887262
1,31129,285.450346,2.0,1.697761,0.0,3.731602,4.929186,0.527631,3.887809,4.693141,0.928562,3.740758,6.146441,7.274979,8.006457,0.000000,45.564326
2,31130,0.000000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31131,264.711316,2.0,3.115103,0.0,5.000000,1.320674,0.000000,3.141062,4.071959,2.052399,0.684985,2.297100,9.512964,0.438428,3.919226,35.553899
4,31132,1353.348730,3.0,3.509081,0.0,5.000000,5.000000,5.000000,4.448512,5.000000,0.000000,2.050769,7.369489,8.887880,8.186877,9.099088,63.551696

In [ ]:
dataset1 = pd.merge(DF_DEMO_PHQ, DF_PAG_HEI, how='outer') #sem definir SEQN COMO ID
dataset1.head

<bound method NDFrame.head of        SEQN  DPQ010  DPQ020  DPQ030  DPQ040  DPQ050  DPQ060  DPQ070  DPQ080  \
0     31130     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1     31131     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
2     31132     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
3     31134     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
4     31139     0.0     0.0     0.0     0.0     3.0     1.0     0.0     0.0
...     ...     ...     ...     ...     ...     ...     ...     ...     ...
9419  41453     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
9420  41456     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
9421  41467     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
9422  41471     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
9423  41474     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

      DPQ090  ...  HEI2015C5_WHOLEGRAIN  HEI2015C6_TOTALDAIRY  \
0        NaN  ...                   NaN                   NaN
1        0.0  ...              0.000000              3.141062
2        0.0  ...              5.000000              4.448512
3        0.0  ...              2.217331              2.313900
4        0.0  ...              0.211544              0.000000
...      ...  ...                   ...                   ...
9419     NaN  ...                   NaN                   NaN
9420     NaN  ...              3.828484              5.000000
9421     NaN  ...              0.000000              5.000000
9422     NaN  ...              0.463168              4.662005
9423     NaN  ...              5.000000              5.000000

      HEI2015C7_TOTPROT  HEI2015C8_SEAPLANT_PROT  HEI2015C9_FATTYACID  \
0                   NaN                      NaN                  NaN
1              4.071959                 2.052399             0.684985
2              5.000000                 0.000000             2.050769
3              5.000000                 1.268648             2.958985
4              4.088849                 4.221442            10.000000
...                 ...                      ...                  ...
9419                NaN                      NaN                  NaN
9420           3.116386                 5.000000             0.000000
9421           5.000000                 0.000000             6.098940
9422           5.000000                 1.191796             6.145146
9423           4.304982                 5.000000             2.162293

      HEI2015C10_SODIUM  HEI2015C11_REFINEDGRAIN  HEI2015C12_SFAT  \
0                   NaN                      NaN              NaN
1              2.297100                 9.512964         0.438428
2              7.369489                 8.887880         8.186877
3              0.000000                 5.627488         5.863078
4              2.845774                 0.000000        10.000000
...                 ...                      ...              ...
9419                NaN                      NaN              NaN
9420          10.000000                10.000000         3.091836
9421           0.476004                 0.000000         7.513204
9422           3.189620                 3.766149         3.974279
9423           7.018993                10.000000         7.541082

      HEI2015C13_ADDSUG  HEI2015_TOTAL_SCORE
0                   NaN                  NaN
1              3.919226            35.553899
2              9.099088            63.551696
3              5.878686            42.886826
4              9.658507            47.074393
...                 ...                  ...
9419                NaN                  NaN
9420           2.718813            55.556054
9421           9.693030            44.844719
9422           7.758940            45.310883
9423           0.000000            52.805494

[9424 rows x 31 columns]>

A soma dos dados dos dois dataset dão 9.424 rows e 31 columns

# chave única

In [ ]:
dataset2 = dataset1.set_index(['SEQN']).sort_index()
dataset2

,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,RIAGENDR,...,HEI2015C5_WHOLEGRAIN,HEI2015C6_TOTALDAIRY,HEI2015C7_TOTPROT,HEI2015C8_SEAPLANT_PROT,HEI2015C9_FATTYACID,HEI2015C10_SODIUM,HEI2015C11_REFINEDGRAIN,HEI2015C12_SFAT,HEI2015C13_ADDSUG,HEI2015_TOTAL_SCORE
SEQN,,,,,,,,,,,,,,,,,,,,,
31128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,5.000000,4.251329,0.000000,2.487572,6.911882,10.000000,0.818029,6.408092,47.887262
31129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.527631,3.887809,4.693141,0.928562,3.740758,6.146441,7.274979,8.006457,0.000000,45.564326
31130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.000000,3.141062,4.071959,2.052399,0.684985,2.297100,9.512964,0.438428,3.919226,35.553899
31132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,5.000000,4.448512,5.000000,0.000000,2.050769,7.369489,8.887880,8.186877,9.099088,63.551696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41469,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.000000,2.151846,5.000000,0.000000,9.344947,3.535211,4.326307,5.269780,8.195564,42.993323
41471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.463168,4.662005,5.000000,1.191796,6.145146,3.189620,3.766149,3.974279,7.758940,45.310883
41472,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.933303,5.000000,5.000000,5.000000,2.090534,8.409844,8.936854,3.063795,0.000000,46.134467
41473,0.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.000000,5.000000,5.000000,5.000000,0.000000,7.458058,10.000000,1.676912,2.751168,45.793478
41474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,5.000000,4.304982,5.000000,2.162293,7.018993,10.000000,7.541082,0.000000,52.805494

In [ ]:
dataset2.columns

Index(['DPQ010', 'DPQ020', 'DPQ030', 'DPQ040', 'DPQ050', 'DPQ060', 'DPQ070',
       'DPQ080', 'DPQ090', 'RIAGENDR', 'RIDAGEYR', 'RIDRETH1', 'DMDEDUC',
       'INDFMINC', 'PAG_MINW', 'ADHERENCE', 'HEI2015C1_TOTALVEG',
       'HEI2015C2_GREEN_AND_BEAN', 'HEI2015C3_TOTALFRUIT',
       'HEI2015C4_WHOLEFRUIT', 'HEI2015C5_WHOLEGRAIN', 'HEI2015C6_TOTALDAIRY',
       'HEI2015C7_TOTPROT', 'HEI2015C8_SEAPLANT_PROT', 'HEI2015C9_FATTYACID',
       'HEI2015C10_SODIUM', 'HEI2015C11_REFINEDGRAIN', 'HEI2015C12_SFAT',
       'HEI2015C13_ADDSUG', 'HEI2015_TOTAL_SCORE'],
      dtype='object')

In [ ]:
dataset2.head(10)

,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,RIAGENDR,...,HEI2015C5_WHOLEGRAIN,HEI2015C6_TOTALDAIRY,HEI2015C7_TOTPROT,HEI2015C8_SEAPLANT_PROT,HEI2015C9_FATTYACID,HEI2015C10_SODIUM,HEI2015C11_REFINEDGRAIN,HEI2015C12_SFAT,HEI2015C13_ADDSUG,HEI2015_TOTAL_SCORE
SEQN,,,,,,,,,,,,,,,,,,,,,
31128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,5.000000,4.251329,0.000000,2.487572,6.911882,10.000000,0.818029,6.408092,47.887262
31129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.527631,3.887809,4.693141,0.928562,3.740758,6.146441,7.274979,8.006457,0.000000,45.564326
31130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.000000,3.141062,4.071959,2.052399,0.684985,2.297100,9.512964,0.438428,3.919226,35.553899
31132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,5.000000,4.448512,5.000000,0.000000,2.050769,7.369489,8.887880,8.186877,9.099088,63.551696
31133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,3.176179,3.617204,0.470430,5.657701,5.589008,0.000000,6.473871,5.779322,35.581653
31134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,2.217331,2.313900,5.000000,1.268648,2.958985,0.000000,5.627488,5.863078,5.878686,42.886826
31136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.676749,5.000000,3.526000,0.000000,4.379950,8.192344,7.032194,5.461700,0.000000,36.613702
31138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.558511,5.000000,4.079000,0.000000,7.149274,2.288504,5.801370,7.816354,7.899627,54.982037

somente idade maiores  ou igual a 18 **RIDAGEYR**

In [ ]:
dataset3 = dataset2[dataset2['RIDAGEYR'] >= 18]

In [ ]:
dataset3['RIDAGEYR'].describe()

count    5334.000000
mean       45.089989
std        20.145853
min        18.000000
25%        27.000000
50%        43.000000
75%        62.000000
max        85.000000
Name: RIDAGEYR, dtype: float64

# PHQ9

criar a nova variável, phq9 - escore Patient Health Questionnaire-9

como a soma das variáveis DPQ010 a DPQ090

In [ ]:
dataset3['phq9'] = dataset3['DPQ010'] + dataset3['DPQ090']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
dataset3

,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,RIAGENDR,...,HEI2015C6_TOTALDAIRY,HEI2015C7_TOTPROT,HEI2015C8_SEAPLANT_PROT,HEI2015C9_FATTYACID,HEI2015C10_SODIUM,HEI2015C11_REFINEDGRAIN,HEI2015C12_SFAT,HEI2015C13_ADDSUG,HEI2015_TOTAL_SCORE,phq9
SEQN,,,,,,,,,,,,,,,,,,,,,
31130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,3.141062,4.071959,2.052399,0.684985,2.297100,9.512964,0.438428,3.919226,35.553899,0.0
31132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,4.448512,5.000000,0.000000,2.050769,7.369489,8.887880,8.186877,9.099088,63.551696,0.0
31134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,2.313900,5.000000,1.268648,2.958985,0.000000,5.627488,5.863078,5.878686,42.886826,0.0
31139,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,2.0,...,0.000000,4.088849,4.221442,10.000000,2.845774,0.000000,10.000000,9.658507,47.074393,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41466,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,...,2.555736,5.000000,4.672204,4.633477,0.000000,6.580006,8.393244,9.360990,59.949915,0.0
41468,0.0,2.0,0.0,1.0,1.0,2.0,1.0,3.0,0.0,2.0,...,5.000000,3.759596,2.344264,4.780282,3.134216,1.986137,5.850269,10.000000,57.747869,0.0
41469,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,2.151846,5.000000,0.000000,9.344947,3.535211,4.326307,5.269780,8.195564,42.993323,1.0
41472,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,5.000000,5.000000,5.000000,2.090534,8.409844,8.936854,3.063795,0.000000,46.134467,0.0
41473,0.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,5.000000,5.000000,5.000000,0.000000,7.458058,10.000000,1.676912,2.751168,45.793478,0.0

# PHQ_GRP

Por fim, crie a variável phq_grp - grupo de sintomas de depressão que assume 0 (“sem sintomas”) se phq9 < 5, 1 (“sintomas leves”) se 5 <= phq9 < 10, 2 (“sintomas moderados”) se 10 <= phq9 < 15, 3 (“sintomas moderadamente severos”) se 15 <= phq9 < 19 e 4 (“sintomas severos”) se phq9 >= 20

In [ ]:
dataset3['phq9'].unique()

array([nan,  0.,  1.,  2.,  3.,  5.,  4.,  6.,  9., 11.])

In [ ]:
dataset3.loc[dataset3['phq9']<5,'phq_grp'] = 0
dataset3.loc[(dataset3['phq9']>=5) & (dataset3['phq9']<10),  'phq_grp'] = 1
dataset3.loc[(dataset3['phq9']>=10) & (dataset3['phq9']<15), 'phq_grp'] = 2
dataset3.loc[(dataset3['phq9']>=15) & (dataset3['phq9']<19), 'phq_grp'] = 3
dataset3.loc[dataset3['phq9']>=20,'phq_grp'] = 4

dataset3.head(30)

#método alternativo, porém e necessário x,y
#dataset3['phq_grp'] = np.where((dataset3.phq9 > 5.1) & (dataset3.phq9 < 10), 1,0) #fonte https://pt.stackoverflow.com/questions/436720/python-np-where-com-duas-condi%C3%A7%C3%B5es
#dataset3['phq_grp'] = np.where((dataset3.phq9 >=10) & (dataset3.phq9 <15),2,0)

In [ ]:
dataset3['phq_grp'].unique()

array([0, 1, 2])

# ANÁLISE UNIVARIADA

In [ ]:
dataset3.describe()

,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,RIAGENDR,...,HEI2015C7_TOTPROT,HEI2015C8_SEAPLANT_PROT,HEI2015C9_FATTYACID,HEI2015C10_SODIUM,HEI2015C11_REFINEDGRAIN,HEI2015C12_SFAT,HEI2015C13_ADDSUG,HEI2015_TOTAL_SCORE,phq9,phq_grp
count,4836.000000,4836.000000,4836.000000,4836.000000,4836.000000,4836.000000,4836.000000,4836.000000,4836.000000,5334.000000,...,5060.000000,5060.000000,5060.000000,5060.000000,5060.000000,5060.000000,5060.000000,5060.000000,4836.000000,5334.000000
mean,0.307279,0.313069,0.551282,0.717328,0.320720,0.209884,0.230356,0.147849,0.050248,1.519873,...,4.434237,2.593381,4.706986,4.762261,5.798963,6.067985,6.220367,49.971421,0.357527,0.005812
std,0.758459,0.710683,0.931166,0.913711,0.743057,0.624552,0.639186,0.590390,0.326933,0.499652,...,1.008311,2.171836,3.237059,3.420252,3.496261,3.178186,3.330305,12.324533,0.899136,0.080803
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.059212,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,4.171156,0.000000,2.023710,1.587909,2.925413,3.697080,3.724867,41.032289,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,...,5.000000,2.588240,4.430397,4.833553,6.234319,6.414811,6.864138,49.512445,0.000000,0.000000
75%,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,...,5.000000,5.000000,7.270784,7.650807,9.253265,8.997076,9.454234,58.168013,0.000000,0.000000
max,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,2.000000,...,5.000000,5.000000,10.000000,10.000000,10.000000,10.000000,10.000000,89.529383,11.000000,2.000000

In [ ]:
dataset3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5334 entries, 31130 to 41473
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DPQ010                    4836 non-null   float64
 1   DPQ020                    4836 non-null   float64
 2   DPQ030                    4836 non-null   float64
 3   DPQ040                    4836 non-null   float64
 4   DPQ050                    4836 non-null   float64
 5   DPQ060                    4836 non-null   float64
 6   DPQ070                    4836 non-null   float64
 7   DPQ080                    4836 non-null   float64
 8   DPQ090                    4836 non-null   float64
 9   RIAGENDR                  5334 non-null   float64
 10  RIDAGEYR                  5334 non-null   float64
 11  RIDRETH1                  5334 non-null   float64
 12  DMDEDUC                   5334 non-null   float64
 13  INDFMINC                  5287 non-null   float64
 14  PAG_MINW                  5334 non-null   float64
 15  ADHERENCE                 5334 non-null   float64
 16  HEI2015C1_TOTALVEG        5060 non-null   float64
 17  HEI2015C2_GREEN_AND_BEAN  5060 non-null   float64
 18  HEI2015C3_TOTALFRUIT      5060 non-null   float64
 19  HEI2015C4_WHOLEFRUIT      5060 non-null   float64
 20  HEI2015C5_WHOLEGRAIN      5060 non-null   float64
 21  HEI2015C6_TOTALDAIRY      5060 non-null   float64
 22  HEI2015C7_TOTPROT         5060 non-null   float64
 23  HEI2015C8_SEAPLANT_PROT   5060 non-null   float64
 24  HEI2015C9_FATTYACID       5060 non-null   float64
 25  HEI2015C10_SODIUM         5060 non-null   float64
 26  HEI2015C11_REFINEDGRAIN   5060 non-null   float64
 27  HEI2015C12_SFAT           5060 non-null   float64
 28  HEI2015C13_ADDSUG         5060 non-null   float64
 29  HEI2015_TOTAL_SCORE       5060 non-null   float64
 30  phq9                      4836 non-null   float64
 31  phq_grp                   5334 non-null   int64
 32  D                         5334 non-null   bool
dtypes: bool(1), float64(31), int64(1)
memory usage: 1.3 MB

In [ ]:
dataset3.isnull().sum()

DPQ010                      498
DPQ020                      498
DPQ030                      498
DPQ040                      498
DPQ050                      498
DPQ060                      498
DPQ070                      498
DPQ080                      498
DPQ090                      498
RIAGENDR                      0
RIDAGEYR                      0
RIDRETH1                      0
DMDEDUC                       0
INDFMINC                     47
PAG_MINW                      0
ADHERENCE                     0
HEI2015C1_TOTALVEG          274
HEI2015C2_GREEN_AND_BEAN    274
HEI2015C3_TOTALFRUIT        274
HEI2015C4_WHOLEFRUIT        274
HEI2015C5_WHOLEGRAIN        274
HEI2015C6_TOTALDAIRY        274
HEI2015C7_TOTPROT           274
HEI2015C8_SEAPLANT_PROT     274
HEI2015C9_FATTYACID         274
HEI2015C10_SODIUM           274
HEI2015C11_REFINEDGRAIN     274
HEI2015C12_SFAT             274
HEI2015C13_ADDSUG           274
HEI2015_TOTAL_SCORE         274
phq9                        498
phq_grp                       0
D                             0
dtype: int64

In [ ]:
#DPQ
dataset3.iloc[:, 0:9]

       DPQ010  DPQ020  DPQ030  DPQ040  DPQ050  DPQ060  DPQ070  DPQ080  DPQ090
SEQN
31130     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
31131     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
31132     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
31134     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
31139     0.0     0.0     0.0     0.0     3.0     1.0     0.0     0.0     0.0
...       ...     ...     ...     ...     ...     ...     ...     ...     ...
41466     0.0     0.0     1.0     1.0     0.0     0.0     0.0     0.0     0.0
41468     0.0     2.0     0.0     1.0     1.0     2.0     1.0     3.0     0.0
41469     1.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0
41472     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
41473     0.0     0.0     2.0     1.0     0.0     1.0     0.0     0.0     0.0

[5334 rows x 9 columns]

In [ ]:
#displot

#ANÁLISE BIVARIADA